// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cw1_9518_proxy.DTO;

#nullable disable

namespace cw1_9518_proxy.Migrations
{
    [DbContext(typeof(HotelDbContext))]
    [Migration("20221107042612_Initialize")]
    partial class Initialize
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("cw1_9518_proxy.DTO.Room", b =>
                {
                    b.Property<int>("RoomId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomId"), 1L, 1);

                    b.Property<string>("Brief")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RoomNumber")
                        .HasColumnType("int");

                    b.HasKey("RoomId");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomId = 1,
                            Brief = "brief_1",
                            Floor = 1,
                            IsAvailable = true,
                            Price = 0.76696311821167396,
                            RoomNumber = 22
                        },
                        new
                        {
                            RoomId = 2,
                            Brief = "brief_2",
                            Floor = 5,
                            IsAvailable = false,
                            Price = 0.88668765768315505,
                            RoomNumber = 3
                        },
                        new
                        {
                            RoomId = 3,
                            Brief = "brief_3",
                            Floor = 6,
                            IsAvailable = true,
                            Price = 0.24889493555394437,
                            RoomNumber = 8
                        },
                        new
                        {
                            RoomId = 4,
                            Brief = "brief_4",
                            Floor = 2,
                            IsAvailable = false,
                            Price = 0.86879041345043517,
                            RoomNumber = 28
                        },
                        new
                        {
                            RoomId = 5,
                            Brief = "brief_5",
                            Floor = 8,
                            IsAvailable = true,
                            Price = 0.25784547802205482,
                            RoomNumber = 9
                        },
                        new
                        {
                            RoomId = 6,
                            Brief = "brief_6",
                            Floor = 4,
                            IsAvailable = false,
                            Price = 0.17042370755566127,
                            RoomNumber = 19
                        },
                        new
                        {
                            RoomId = 7,
                            Brief = "brief_7",
                            Floor = 8,
                            IsAvailable = true,
                            Price = 0.28597552837573836,
                            RoomNumber = 24
                        },
                        new
                        {
                            RoomId = 8,
                            Brief = "brief_8",
                            Floor = 3,
                            IsAvailable = false,
                            Price = 0.96934628323475613,
                            RoomNumber = 10
                        },
                        new
                        {
                            RoomId = 9,
                            Brief = "brief_9",
                            Floor = 6,
                            IsAvailable = true,
                            Price = 0.47955751113877765,
                            RoomNumber = 1
                        },
                        new
                        {
                            RoomId = 10,
                            Brief = "brief_10",
                            Floor = 5,
                            IsAvailable = false,
                            Price = 0.079575754786231245,
                            RoomNumber = 4
                        },
                        new
                        {
                            RoomId = 11,
                            Brief = "brief_11",
                            Floor = 9,
                            IsAvailable = true,
                            Price = 0.85463665729940663,
                            RoomNumber = 1
                        },
                        new
                        {
                            RoomId = 12,
                            Brief = "brief_12",
                            Floor = 9,
                            IsAvailable = false,
                            Price = 0.96796510652898482,
                            RoomNumber = 12
                        },
                        new
                        {
                            RoomId = 13,
                            Brief = "brief_13",
                            Floor = 8,
                            IsAvailable = true,
                            Price = 0.67691149353084901,
                            RoomNumber = 26
                        },
                        new
                        {
                            RoomId = 14,
                            Brief = "brief_14",
                            Floor = 7,
                            IsAvailable = false,
                            Price = 0.90530577345663643,
                            RoomNumber = 6
                        },
                        new
                        {
                            RoomId = 15,
                            Brief = "brief_15",
                            Floor = 7,
                            IsAvailable = true,
                            Price = 0.36340254945103179,
                            RoomNumber = 2
                        },
                        new
                        {
                            RoomId = 16,
                            Brief = "brief_16",
                            Floor = 3,
                            IsAvailable = false,
                            Price = 0.60933481461876349,
                            RoomNumber = 9
                        },
                        new
                        {
                            RoomId = 17,
                            Brief = "brief_17",
                            Floor = 3,
                            IsAvailable = true,
                            Price = 0.65941000956701745,
                            RoomNumber = 23
                        },
                        new
                        {
                            RoomId = 18,
                            Brief = "brief_18",
                            Floor = 4,
                            IsAvailable = false,
                            Price = 0.72161574115824079,
                            RoomNumber = 23
                        },
                        new
                        {
                            RoomId = 19,
                            Brief = "brief_19",
                            Floor = 3,
                            IsAvailable = true,
                            Price = 0.82358504260502929,
                            RoomNumber = 16
                        },
                        new
                        {
                            RoomId = 20,
                            Brief = "brief_20",
                            Floor = 4,
                            IsAvailable = false,
                            Price = 0.94381975354982284,
                            RoomNumber = 10
                        },
                        new
                        {
                            RoomId = 21,
                            Brief = "brief_21",
                            Floor = 2,
                            IsAvailable = true,
                            Price = 0.64421689565450069,
                            RoomNumber = 27
                        },
                        new
                        {
                            RoomId = 22,
                            Brief = "brief_22",
                            Floor = 5,
                            IsAvailable = false,
                            Price = 0.19189835978909098,
                            RoomNumber = 15
                        },
                        new
                        {
                            RoomId = 23,
                            Brief = "brief_23",
                            Floor = 4,
                            IsAvailable = true,
                            Price = 0.71470846174872882,
                            RoomNumber = 19
                        },
                        new
                        {
                            RoomId = 24,
                            Brief = "brief_24",
                            Floor = 4,
                            IsAvailable = false,
                            Price = 0.78381983636810626,
                            RoomNumber = 29
                        },
                        new
                        {
                            RoomId = 25,
                            Brief = "brief_25",
                            Floor = 4,
                            IsAvailable = true,
                            Price = 0.37933931012864319,
                            RoomNumber = 2
                        },
                        new
                        {
                            RoomId = 26,
                            Brief = "brief_26",
                            Floor = 4,
                            IsAvailable = false,
                            Price = 0.17156163334379793,
                            RoomNumber = 1
                        },
                        new
                        {
                            RoomId = 27,
                            Brief = "brief_27",
                            Floor = 4,
                            IsAvailable = true,
                            Price = 0.34800023701944027,
                            RoomNumber = 26
                        },
                        new
                        {
                            RoomId = 28,
                            Brief = "brief_28",
                            Floor = 2,
                            IsAvailable = false,
                            Price = 0.22023791644702173,
                            RoomNumber = 14
                        },
                        new
                        {
                            RoomId = 29,
                            Brief = "brief_29",
                            Floor = 4,
                            IsAvailable = true,
                            Price = 0.78676800417937165,
                            RoomNumber = 20
                        },
                        new
                        {
                            RoomId = 30,
                            Brief = "brief_30",
                            Floor = 9,
                            IsAvailable = false,
                            Price = 0.89609204389516295,
                            RoomNumber = 19
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
